from selenium.webdriver.common.by import By


class PremiumPageLocatorsPrice:
    PREMIUM_BUY_BLOCK_SELECTION = By.XPATH, '(//div[contains(@class, "BaseBox")])[2]'
    PREMIUM_BUY_BLOCK_CONTENT_1D_1Y =
    PREMIUM_BUY_BLOCK_CONTENT_3D_1Y =
    PREMIUM_BUY_BLOCK_CONTENT_5D_1Y =
    #PREMIUM_BUY_BLOCK_CONTENT_10D_1Y =
    PREMIUM_BUY_BLOCK_CONTENT_1D_2Y =
    PREMIUM_BUY_BLOCK_CONTENT_3D_2Y =
    PREMIUM_BUY_BLOCK_CONTENT_5D_2Y =
    #PREMIUM_BUY_BLOCK_CONTENT_10D_2Y =
    PREMIUM_NEED_MORE_DEVICES_BUTTON =